#!/usr/bin/env bash
# Displays A records

get_record(){
	local domain="$1"
	local subdomain="$2"

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for subdomain in "${subdomains[@]}"; do
		record=$(dig +short "$subdomain.$domain" A | awk -v subdomain="$subdomain" '{print "The subdomain " subdomain " is a A record and points to " $0}')
		echo "$record"
	done
}
get_record "$@"
