#!/usr/bin/env bash
# Create a certificate using certbot and configure HAproxy to accept encrypted traffic for your subdomain www.

apt-get update
apt-get install -y haproxy

sudo apt intsall snapd
sudo apt-get remove certbot
sudo apt-get install -y certbot

sudo service haproxy stop
sudo certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d www.linus-obura.tech
sudo mkdir -p /etc/haproxy/certs

DOMAIN='www.linus-obura.tech' sudo -E bash -c 'cat /etc/letsencrypt/live/$DOMAIN/fullchain.pem /etc/letsencrypt/live/$DOMAIN/privkey.pem > /etc/haproxy/certs/$DOMAIN.pem'

sudo chmod -R go-rwx /etc/haproxy/certs

echo "
global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

        # Default SSL locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

        ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-S>
        ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
        ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend linus-obura-frontend
        bind *:80
        mode http
        http-request redirect scheme https code 301 unless { ssl_fc }
        http-request set-header X_Forwarded-Proto http
        default_backend web_servers

frontend linus-obura-frontend-https
        bind *:443 ssl crt /etc/haproxy/certs/www.linus-obura.tech.pem
        http-request set-header X-Forwarded-Proto https
        default_backend web_servers

backend web_servers
		balance roundrobin
		server 518233-web-01 3.85.177.85:80 check
		server 518233-web-02 18.206.192.69:80 check
" > /etc/haproxy/haproxy.cfg

service haproxy restart