#!/usr/bin/env bash
# Script to install and configure ngix as per requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
