#!/usr/bin/env bash
# Creates a 404 page


nginx_config="/etc/nginx/sites-available/default"

new_string="location /xyz {\\
\\treturn 404 \"Ceci n\'est pas une page\";\\
}"


sed -i "/server_name _;/a $new_string" "$nginx_config"

sudo service nginx restart