#!/usr/bin/env bash
#Script that uses while and if to say hi if 9

counter=1

while [ $counter -le 10 ]
do
	if [ $counter = 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	((counter++))
done
