#!/usr/bin/env bash
#Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

MY_LIST=$(find . -type f | cut -d'-' -f2-)

for item in ${MY_LIST};
do
	echo "${item}"
done