#!/usr/bin/env bash
# Bash script that configures user nginx to run nginx as nginx
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart